import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import test from 'node:test';

import * as api from '@scene-engine/display';

test('0.21 root is the exact Display public surface and excludes internal Authority mutation types', async () => {
  assert.deepEqual(Object.keys(api).sort(), [
    'ANIMATION_RESOURCE_SCHEMA',
    'AmbientLightComponent',
    'AnimationPlayerComponent',
    'BackgroundComponent',
    'BehaviourComponent',
    'BillboardComponent',
    'CameraComponent',
    'Component',
    'DISPLAY_CATALOG_MANIFEST_SCHEMA',
    'DISPLAY_RUNTIME_SCHEMA',
    'DISPLAY_SUMMARY_SCHEMA',
    'DirectionalLightComponent',
    'DisplayKindDefinition',
    'DisplayRuntime',
    'DisplayRuntimeError',
    'DisplayTransform',
    'GENERATED_TEXTURE_LIMITS',
    'GENERATED_TEXTURE_RESOURCE_SCHEMA',
    'LookAtComponent',
    'MeshRendererComponent',
    'ModelRendererComponent',
    'POINTER_NODE_EVENT_INPUT_COMMAND',
    'POINTER_NODE_EVENT_NAMES',
    'POINTER_TARGET_ROLES',
    'PREFAB_DEFINITION_SCHEMA',
    'PROGRAM_RESOURCE_SCHEMA',
    'ParticleRendererComponent',
    'PointLightComponent',
    'PointerNodeEventHub',
    'PointerTargetComponent',
    'PrefabDefinition',
    'RENDER_COMPOSITION_PASS_KINDS',
    'RENDER_COMPOSITION_SCHEMA',
    'RESOURCE_REGISTRY_SCHEMA',
    'RenderComponent',
    'RenderCompositionComponent',
    'SCENE_DEFINITION_SCHEMA',
    'SceneDefinition',
    'SpotLightComponent',
    'SpriteRendererComponent',
    'SurfaceRendererComponent',
    'TICKS_PER_SECOND',
    'UPPER_FIELD_INVERSE_MARGIN',
    'buildDisplayCatalogManifest',
    'canonicalDisplayCatalogJson',
    'computeDisplayCatalogIdentity',
    'createComponentRegistry',
    'createDisplayKindRegistry',
    'createDisplayRuntime',
    'createPointerInteractionController',
    'createPrefabRegistry',
    'createResourceRegistry',
    'createSceneRegistry',
    'defineAnimation',
    'defineDisplayCatalogManifest',
    'defineDisplayKind',
    'defineFrameAnimation',
    'definePrefab',
    'defineRenderComposition',
    'defineResources',
    'defineScene',
    'deriveUpperFieldProjection',
    'normalizeDisplayCatalogIdentity',
    'normalizePointerNodeEvent',
    'normalizeProgramParameters',
    'normalizeProjectionProfile',
    'pointerNodeEventInput',
    'projectUpperFieldY',
    'sameDisplayCatalogIdentity',
    'toDisplayCatalogIdentityRecord',
    'unprojectUpperFieldY',
  ]);

  for (const removed of [
    ['Local', 'Edit', 'Port'].join(''),
    ['create', 'Local', 'Edit', 'Port'].join(''),
    'AnimationSystem',
  ]) assert.equal(removed in api, false, removed);
  const packageJson = JSON.parse(await fs.readFile(new URL('../package.json', import.meta.url)));
  assert.equal(packageJson.version, '0.21.0');
});
