"""Frozen packed declarations for Scene Bootstrap / Presentation Frame V3.

The V3 presentation profile is intentionally incompatible with V1/V2. Static
and dynamic nodes share the same local-transform record and product profile
payloads remain opaque to Scene Engine.
"""

from __future__ import annotations

import struct


PRESENTATION_TICKS_PER_SECOND = 60

PRESENTATION_SECTION_DIRECTORY_ENTRY_BYTES = 20
PRESENTATION_SECTION_DIRECTORY_ENTRY_V3 = struct.Struct("<HHIIIHH")
PRESENTATION_SECTION_FLAG_REQUIRED = 1 << 0

SCENE_BOOTSTRAP_SCHEMA_VERSION = 3
SCENE_BOOTSTRAP_FLAG_COMPLETE_STATIC_SET = 1 << 0
SCENE_BOOTSTRAP_HEADER_BYTES = 96
SCENE_BOOTSTRAP_HEADER_V3 = struct.Struct("<HHHHQQHHfIIII32s16s")
SCENE_BOOTSTRAP_COORDINATE_PROFILE_RH_Y_UP_Z_FORWARD_XYZW_F32 = 1

BOOTSTRAP_SECTION_IDENTITY = 1
BOOTSTRAP_SECTION_AUTHORITY_BASELINE = 2
BOOTSTRAP_SECTION_STATIC_NODES = 3
BOOTSTRAP_SECTION_NODE_PROFILE_REFS = 4
BOOTSTRAP_SECTION_NODE_PROFILE_BYTES = 5
BOOTSTRAP_SECTION_NODE_INTERACTION_REFS = 6
BOOTSTRAP_SECTION_NODE_INTERACTION_BYTES = 7
BOOTSTRAP_SECTION_SCENE_METADATA_REFS = 8
BOOTSTRAP_SECTION_SCENE_METADATA_BYTES = 9
BOOTSTRAP_SECTION_VISUAL_TYPES = 10
BOOTSTRAP_SECTION_ANIMATION_STATES = 11

BOOTSTRAP_SESSION_IDENTITY_HEADER_V3 = struct.Struct("<HHHIH")
BOOTSTRAP_AUTHORITY_BASELINE_HEADER_V3 = struct.Struct("<HIIH")

PRESENTATION_FRAME_SCHEMA_VERSION = 3
PRESENTATION_FRAME_FLAG_COMPLETE_DYNAMIC_SET = 1 << 0
PRESENTATION_FRAME_HEADER_BYTES = 80
PRESENTATION_FRAME_HEADER_V3 = struct.Struct("<HHHHQQQQQHHIIIIIII")

FRAME_SECTION_DYNAMIC_NODES = 1
FRAME_SECTION_NODE_PROFILE_REFS = 2
FRAME_SECTION_NODE_PROFILE_BYTES = 3
FRAME_SECTION_NODE_INTERACTION_REFS = 4
FRAME_SECTION_NODE_INTERACTION_BYTES = 5
FRAME_SECTION_EVENTS = 6
FRAME_SECTION_EVENT_BYTES = 7

PRESENTATION_NODE_RECORD_BYTES = 80
PRESENTATION_NODE_RECORD_V3 = struct.Struct("<QQII3f4f3fIQI")
PRESENTATION_NODE_FLAG_VISIBLE = 1 << 0
PRESENTATION_NODE_ALLOWED_FLAGS = PRESENTATION_NODE_FLAG_VISIBLE

NODE_PAYLOAD_REF_BYTES = 24
NODE_PAYLOAD_REF_V3 = struct.Struct("<QIIII")
SCENE_METADATA_REF_BYTES = 16
SCENE_METADATA_REF_V3 = struct.Struct("<IIII")

VISUAL_TYPE_RECORD_BYTES = 16
VISUAL_TYPE_RECORD_V3 = struct.Struct("<IIII")
VISUAL_TYPE_FLAG_INTERACTIVE = 1 << 0
VISUAL_TYPE_FLAG_ATTACHMENT = 1 << 1
VISUAL_TYPE_FLAG_EFFECT = 1 << 2
VISUAL_TYPE_ALLOWED_FLAGS = (
    VISUAL_TYPE_FLAG_INTERACTIVE
    | VISUAL_TYPE_FLAG_ATTACHMENT
    | VISUAL_TYPE_FLAG_EFFECT
)

ANIMATION_STATE_RECORD_BYTES = 16
ANIMATION_STATE_RECORD_V3 = struct.Struct("<IIII")
ANIMATION_FLAG_LOOP = 1 << 0
ANIMATION_FLAG_ONCE = 1 << 1
ANIMATION_FLAG_BLEND = 1 << 2
ANIMATION_ALLOWED_FLAGS = ANIMATION_FLAG_LOOP | ANIMATION_FLAG_ONCE | ANIMATION_FLAG_BLEND

PRESENTATION_EVENT_RECORD_BYTES = 48
PRESENTATION_EVENT_RECORD_V3 = struct.Struct("<QIIQQQII")
PRESENTATION_EVENT_FLAG_ONCE = 1 << 0
PRESENTATION_EVENT_ALLOWED_FLAGS = PRESENTATION_EVENT_FLAG_ONCE


def _assert_frozen_sizes() -> None:
    expected = (
        (PRESENTATION_SECTION_DIRECTORY_ENTRY_V3, PRESENTATION_SECTION_DIRECTORY_ENTRY_BYTES),
        (SCENE_BOOTSTRAP_HEADER_V3, SCENE_BOOTSTRAP_HEADER_BYTES),
        (PRESENTATION_FRAME_HEADER_V3, PRESENTATION_FRAME_HEADER_BYTES),
        (PRESENTATION_NODE_RECORD_V3, PRESENTATION_NODE_RECORD_BYTES),
        (NODE_PAYLOAD_REF_V3, NODE_PAYLOAD_REF_BYTES),
        (SCENE_METADATA_REF_V3, SCENE_METADATA_REF_BYTES),
        (VISUAL_TYPE_RECORD_V3, VISUAL_TYPE_RECORD_BYTES),
        (ANIMATION_STATE_RECORD_V3, ANIMATION_STATE_RECORD_BYTES),
        (PRESENTATION_EVENT_RECORD_V3, PRESENTATION_EVENT_RECORD_BYTES),
    )
    for declaration, byte_count in expected:
        if declaration.size != byte_count:  # pragma: no cover - import guard
            raise RuntimeError(
                "packed V3 declaration has size {} instead of {}".format(
                    declaration.size, byte_count
                )
            )


_assert_frozen_sizes()


__all__ = [name for name in globals() if name.isupper()]
