"""Frozen binary declarations for the ordered presentation profile.

The standalone display-frame V1 declarations remain an immutable experimental
slice.  Production uses Bootstrap V2 and DisplayFrame V2; several packed
record constants retain a ``V1`` suffix solely as their physical-layout
revision and are shared by the V2 Bootstrap/frame schemas.
"""

from __future__ import annotations

import struct


PRESENTATION_TICKS_PER_SECOND = 60

SCENE_BOOTSTRAP_SCHEMA_VERSION = 1
SCENE_BOOTSTRAP_SCHEMA_VERSION_V2 = 2
SCENE_BOOTSTRAP_FLAG_COMPLETE_STATIC_SET = 1 << 0
SCENE_BOOTSTRAP_HEADER_BYTES = 96
SCENE_BOOTSTRAP_COORDINATE_PROFILE_RH_Y_UP_Z_FORWARD_XYZW_F32 = 1
SCENE_BOOTSTRAP_HEADER_V1 = struct.Struct("<HHHHQQHHfIIII32s16s")

PRESENTATION_SECTION_DIRECTORY_ENTRY_BYTES = 20
PRESENTATION_SECTION_FLAG_REQUIRED = 1 << 0
PRESENTATION_SECTION_DIRECTORY_ENTRY_V1 = struct.Struct("<HHIIIHH")

BOOTSTRAP_SECTION_IDENTITY = 1
BOOTSTRAP_SECTION_STATIC_NODES = 2
BOOTSTRAP_SECTION_TOPOLOGY_NODES = 3
BOOTSTRAP_SECTION_ADJACENCIES = 4
BOOTSTRAP_SECTION_VISUAL_REGISTRY = 5
BOOTSTRAP_SECTION_ANIMATION_REGISTRY = 6
BOOTSTRAP_SECTION_AUTHORITY_BASELINE = 7

BOOTSTRAP_IDENTITY_HEADER_BYTES = 32
BOOTSTRAP_IDENTITY_HEADER_V1 = struct.Struct("<HHHHHHIQQ")
BOOTSTRAP_SESSION_IDENTITY_HEADER_V2 = struct.Struct("<HHHIH")
BOOTSTRAP_AUTHORITY_BASELINE_HEADER_V2 = struct.Struct("<HIIH")
STATIC_NODE_RECORD_BYTES = 80
STATIC_NODE_RECORD_V1 = struct.Struct("<QQIIII3f4f3fII")
STATIC_NODE_FLAG_VISIBLE = 1 << 0
STATIC_NODE_ALLOWED_FLAGS = STATIC_NODE_FLAG_VISIBLE
TOPOLOGY_NODE_RECORD_BYTES = 32
# The final uint32 is reserved topology flags and must remain zero in v1.
TOPOLOGY_NODE_RECORD_V1 = struct.Struct("<QIIiiII")
ADJACENCY_RECORD_BYTES = 16
ADJACENCY_RECORD_V1 = struct.Struct("<QQ")
VISUAL_REGISTRY_RECORD_BYTES = 32
VISUAL_REGISTRY_RECORD_V1 = struct.Struct("<IIIIIIII")
VISUAL_CAPABILITY_INTERACTIVE = 1 << 0
VISUAL_CAPABILITY_ATTACHMENT = 1 << 1
VISUAL_CAPABILITY_EFFECT = 1 << 2
VISUAL_CAPABILITY_ALLOWED = (
    VISUAL_CAPABILITY_INTERACTIVE
    | VISUAL_CAPABILITY_ATTACHMENT
    | VISUAL_CAPABILITY_EFFECT
)
ANIMATION_REGISTRY_RECORD_BYTES = 16
ANIMATION_REGISTRY_RECORD_V1 = struct.Struct("<IIII")
ANIMATION_FLAG_LOOP = 1 << 0
ANIMATION_FLAG_ONCE = 1 << 1
ANIMATION_FLAG_BLEND = 1 << 2
ANIMATION_ALLOWED_FLAGS = ANIMATION_FLAG_LOOP | ANIMATION_FLAG_ONCE | ANIMATION_FLAG_BLEND

PRESENTATION_FRAME_SCHEMA_VERSION = 2
PRESENTATION_FRAME_FLAG_COMPLETE_DYNAMIC_SET = 1 << 0
PRESENTATION_FRAME_HEADER_BYTES = 80
PRESENTATION_FRAME_HEADER_V2 = struct.Struct("<HHHHQQQQQHHIIIIIII")

PRESENTATION_SECTION_DYNAMIC_ENTITIES = 1
PRESENTATION_SECTION_OWNER_STATES = 2
PRESENTATION_SECTION_INTERACTIONS = 3
PRESENTATION_SECTION_INTERACTION_STRINGS = 4
PRESENTATION_SECTION_EVENTS = 5

PRESENTATION_ENTITY_RECORD_BYTES = 72
PRESENTATION_ENTITY_RECORD_V2 = struct.Struct("<QII3f4f3fIQI")
PRESENTATION_ENTITY_FLAG_VISIBLE = 1 << 0
PRESENTATION_ENTITY_FLAG_TELEPORT = 1 << 1
PRESENTATION_ENTITY_FLAG_INTERACTIVE = 1 << 2
PRESENTATION_ENTITY_ALLOWED_FLAGS = (
    PRESENTATION_ENTITY_FLAG_VISIBLE
    | PRESENTATION_ENTITY_FLAG_TELEPORT
    | PRESENTATION_ENTITY_FLAG_INTERACTIVE
)

OWNER_STATE_RECORD_BYTES = 64
OWNER_STATE_RECORD_V1 = struct.Struct("<QQIIIIIIII3fI")

INTERACTION_RECORD_BYTES = 32
INTERACTION_RECORD_V1 = struct.Struct("<QIIIIii")
INTERACTION_DOMAIN_ENTITY_ID = 1
INTERACTION_DOMAIN_PERSON_ID = 2
INTERACTION_DOMAIN_TILE_REF = 3
INTERACTION_DOMAIN_KINDS = frozenset(
    (
        INTERACTION_DOMAIN_ENTITY_ID,
        INTERACTION_DOMAIN_PERSON_ID,
        INTERACTION_DOMAIN_TILE_REF,
    )
)

PRESENTATION_EVENT_RECORD_BYTES = 40
PRESENTATION_EVENT_RECORD_V1 = struct.Struct("<QIIQQQ")
PRESENTATION_EVENT_FLAG_ONCE = 1 << 0
PRESENTATION_EVENT_ALLOWED_FLAGS = PRESENTATION_EVENT_FLAG_ONCE


def _assert_frozen_sizes() -> None:
    expected = (
        (SCENE_BOOTSTRAP_HEADER_V1, SCENE_BOOTSTRAP_HEADER_BYTES),
        (
            PRESENTATION_SECTION_DIRECTORY_ENTRY_V1,
            PRESENTATION_SECTION_DIRECTORY_ENTRY_BYTES,
        ),
        (BOOTSTRAP_IDENTITY_HEADER_V1, BOOTSTRAP_IDENTITY_HEADER_BYTES),
        (STATIC_NODE_RECORD_V1, STATIC_NODE_RECORD_BYTES),
        (TOPOLOGY_NODE_RECORD_V1, TOPOLOGY_NODE_RECORD_BYTES),
        (ADJACENCY_RECORD_V1, ADJACENCY_RECORD_BYTES),
        (VISUAL_REGISTRY_RECORD_V1, VISUAL_REGISTRY_RECORD_BYTES),
        (ANIMATION_REGISTRY_RECORD_V1, ANIMATION_REGISTRY_RECORD_BYTES),
        (PRESENTATION_FRAME_HEADER_V2, PRESENTATION_FRAME_HEADER_BYTES),
        (PRESENTATION_ENTITY_RECORD_V2, PRESENTATION_ENTITY_RECORD_BYTES),
        (OWNER_STATE_RECORD_V1, OWNER_STATE_RECORD_BYTES),
        (INTERACTION_RECORD_V1, INTERACTION_RECORD_BYTES),
        (PRESENTATION_EVENT_RECORD_V1, PRESENTATION_EVENT_RECORD_BYTES),
    )
    for declaration, byte_count in expected:
        if declaration.size != byte_count:  # pragma: no cover - import guard
            raise RuntimeError(
                "packed presentation declaration has size {} instead of {}".format(
                    declaration.size, byte_count
                )
            )


_assert_frozen_sizes()


__all__ = [name for name in globals() if name.isupper()]
